[build]
command = "npm run build"
publish = "/build"
base = "/"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[plugins]]
package = "@netlify/plugin-functions-install-core"`
Use this code in your netlify.toml and just deploy on netlify